### ISSUE TITLE
cropping not taking effect

### ISSUE THREAD

**Issue by ghost** [micschk/silverstripe-focuspointcropper#2]
The interface looks all right and the drag and resize work pretty good, but unfortunately when I save the image, it seems the cropping doesn’t take effect, even though i saved the image before cropping as the doc says.

**Comment by micschk** [comment]
Did you re-publish the page as well?

**Comment by ghost** [comment]
yea, I did. I also use the ^2.1 version of silverstripe-focuspoint as the dependency specifies.

**Comment by GarryYeatman-CORE** [comment]
I am also getting this error.

**Comment by micschk** [comment]
I'll look into this as soon as I can find the time (hopefully this week).
In the mean time, could you please let me know the exact version of your framework, cms & focuspoint (or just copy-paste the relevant parts of you composer.json file)?

**Comment by ghost** [comment]
Sorry about the late reply. The framework and cms are both using version 3.3.0. The focuspoint is version 2.1

**Comment by micschk** [comment]
I've just fixed a bug in the cropping which prevented the cropping if either the crop-width or crop-height would be equal to the original image width/height. I expect this bug resolved in 1.5.
