### ISSUE TITLE
Unknown column 'Image.CropData' in 'field list'

### ISSUE THREAD

**Issue by mspacemedia** [micschk/silverstripe-focuspointcropper#4]
Everytime I install, /dev/build?flush=1 and run this, when I then try and view an item with an image field I get this error. Removing Focus Point Cropper and just running with Focus Point works fine, is there an extension that needs to be configured somewhere?

**Comment by micschk** [comment]
I'll look into this as soon as I can find the time (hopefully this week).
In the mean time, could you please let me know the exact version of your framework, cms & focuspoint (or just copy-paste the relevant parts of you composer.json file)?

**Comment by micschk** [comment]
Via e-mail (todo: add clarification to README)
> Okay, not to worry - I removed my FPImage injector from my config.yml and used the config.yml from FocusPoint to inject and it worked fine…

**Comment by mspacemedia** [comment]
Almost, the cropper doesn't respect the upscale property as php always sends the variable across as a string this does not then work with the 

If ($upscale)

test as there is always an upscale variable being passed now in the latest focus point parent method.

Once that is dealt with the images returned are cropped but seem to have issues with the crop area and scaling...

**Comment by micschk** [comment]
Fixed in 1.5
